### ISSUE TITLE
Meetup needs the callback uri to not contain query args when requesting access token

### ISSUE THREAD

**Issue by brachetti** [tapster/omniauth-meetup#5]
I always get the error **invalid_client** when using the gem as it is right now.

Managed to debug that down to the issue of the redirect_uri not matching the one at meetup.com exactly.

**Comment by AdnanTheExcellent** [comment]
I came across this same problem. thanks for the solutions brachetti! However, it did not work in rails 5. I had to copy over the entire auth_code module (it was giving me an error because it couldnt find the authorize_url function) and i had to change params['redirect_uri'] to params[:redirect_uri]

**Comment by duduribeiro** [comment]
Hey @AdnanTheExcellent, is this on your Github?

I'm using Rails5 too, and had the same problem.. I tried to reimplement it, but without success (keep receiving invalid_client 😞 )

thanks a lot
🍻

**Comment by AdnanTheExcellent** [comment]
It isn't, but i'll push it up soon.

**Comment by AdnanTheExcellent** [comment]
hey @duduribeiro you cna find my fork [here](https://github.com/AdnanTheExcellent/omniauth-meetup). If that doesnt work then it is probably some configuration on your end. good luck!

**Comment by gauravtiwari** [comment]
Should be fixed by in this PR #7

**Comment by brachetti** [comment]
In this case I will close this Issue
